# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-23 01:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answertext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('publisher', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Codefirst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Codesecond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('first_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondcodes', to='cq.Codefirst')),
            ],
        ),
        migrations.CreateModel(
            name='Judgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='cq.Article')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('intention', models.CharField(default='no intention', max_length=1024)),
                ('created_step', models.IntegerField(default=0)),
                ('removed_step', models.IntegerField(default=0)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cq.Article')),
                ('code_first', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cq.Codefirst')),
                ('code_second', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cq.Codesecond')),
                ('copied_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cq.Question')),
                ('questioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reftext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reftexts', to='cq.Question')),
                ('questioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reftexts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('author', models.CharField(max_length=1024)),
                ('link', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('paragraph_order', models.IntegerField()),
                ('order', models.IntegerField()),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='cq.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Shown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showns', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='showns', to='cq.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField()),
                ('question_first', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='similaritys_first', to='cq.Question')),
                ('question_second', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='similaritys_second', to='cq.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Take',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken', models.BooleanField()),
                ('shown', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='takes', to='cq.Shown')),
            ],
        ),
        migrations.AddField(
            model_name='reftext',
            name='sentence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reftexts', to='cq.Sentence'),
        ),
        migrations.AddField(
            model_name='judgement',
            name='question_first',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judgements_first', to='cq.Question'),
        ),
        migrations.AddField(
            model_name='judgement',
            name='question_second',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judgements_second', to='cq.Question'),
        ),
        migrations.AddField(
            model_name='judgement',
            name='questioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judgements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='judgement',
            name='similarity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judgements', to='cq.Similarity'),
        ),
        migrations.AddField(
            model_name='article',
            name='research',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='cq.Research'),
        ),
        migrations.AddField(
            model_name='answertext',
            name='sentence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answertexts', to='cq.Sentence'),
        ),
        migrations.AddField(
            model_name='answertext',
            name='take',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answertexts', to='cq.Take'),
        ),
    ]
