# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-21 12:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answertext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Codefirst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Codesecond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('first_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondcodes', to='cq.Codefirst')),
            ],
        ),
        migrations.CreateModel(
            name='Judgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reftext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Shown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='take',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='user',
        ),
        migrations.RemoveField(
            model_name='response',
            name='milestone',
        ),
        migrations.RemoveField(
            model_name='response',
            name='sentence',
        ),
        migrations.RemoveField(
            model_name='response',
            name='user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='owner',
            new_name='questioner',
        ),
        migrations.RenameField(
            model_name='take',
            old_name='remove',
            new_name='taken',
        ),
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='research',
        ),
        migrations.AddField(
            model_name='question',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cq.Article'),
        ),
        migrations.AddField(
            model_name='question',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cq.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='created_step',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='intention',
            field=models.CharField(default='no intention', max_length=1024),
        ),
        migrations.AddField(
            model_name='question',
            name='removed_step',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='research',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='cq.Research'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='cq.Article'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='cq.Article'),
        ),
        migrations.AlterUniqueTogether(
            name='take',
            unique_together=set([]),
        ),
        migrations.DeleteModel(
            name='Milestone',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.AddField(
            model_name='similarity',
            name='question_first',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='similaritys_first', to='cq.Question'),
        ),
        migrations.AddField(
            model_name='similarity',
            name='question_second',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='similaritys_second', to='cq.Question'),
        ),
        migrations.AddField(
            model_name='shown',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='showns', to='cq.Question'),
        ),
        migrations.AddField(
            model_name='reftext',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reftexts', to='cq.Question'),
        ),
        migrations.AddField(
            model_name='reftext',
            name='questioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reftexts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reftext',
            name='sentence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reftexts', to='cq.Sentence'),
        ),
        migrations.AddField(
            model_name='judgement',
            name='question_first',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judgements_first', to='cq.Question'),
        ),
        migrations.AddField(
            model_name='judgement',
            name='question_second',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judgements_second', to='cq.Question'),
        ),
        migrations.AddField(
            model_name='judgement',
            name='questioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judgements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='judgement',
            name='similarity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judgements', to='cq.Similarity'),
        ),
        migrations.AddField(
            model_name='answertext',
            name='sentence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answertexts', to='cq.Sentence'),
        ),
        migrations.AddField(
            model_name='answertext',
            name='take',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answertexts', to='cq.Take'),
        ),
        migrations.RemoveField(
            model_name='take',
            name='article',
        ),
        migrations.RemoveField(
            model_name='take',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='take',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='take',
            name='question',
        ),
        migrations.RemoveField(
            model_name='take',
            name='removed_at',
        ),
        migrations.RemoveField(
            model_name='take',
            name='removed_phase',
        ),
        migrations.RemoveField(
            model_name='take',
            name='user',
        ),
        migrations.AddField(
            model_name='question',
            name='code_first',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cq.Codefirst'),
        ),
        migrations.AddField(
            model_name='question',
            name='code_second',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cq.Codesecond'),
        ),
        migrations.AddField(
            model_name='take',
            name='shown',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='takes', to='cq.Shown'),
        ),
    ]
