# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-29 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='judgement',
            name='question_first',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judgement_firsts', to='cq.Question'),
        ),
        migrations.AlterField(
            model_name='judgement',
            name='question_second',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judgement_seconds', to='cq.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cq.Question'),
        ),
        migrations.AlterField(
            model_name='similarity',
            name='question_first',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='similarity_firsts', to='cq.Question'),
        ),
        migrations.AlterField(
            model_name='similarity',
            name='question_second',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='similarity_seconds', to='cq.Question'),
        ),
    ]
