# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-28 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='cq.Article'),
        ),
    ]
