# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-30 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cq', '0002_auto_20180830_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_step',
            field=models.IntegerField(default=1),
        ),
    ]
