# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-29 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cq', '0002_auto_20180829_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='removed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
