# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-29 15:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cq', '0003_auto_20180829_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
