# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-30 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cq', '0003_question_created_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='take',
            name='remove',
            field=models.BooleanField(default=False),
        ),
    ]
