# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-30 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cq', '0003_auto_20180830_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cq.Article'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='code_first',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cq.Codefirst'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='code_second',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cq.Codesecond'),
            preserve_default=False,
        ),
    ]
