# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-30 01:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cq', '0004_auto_20180730_0139'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='take',
            unique_together=set([]),
        ),
    ]
