# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-29 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cq', '0004_auto_20180829_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='removed_step',
            field=models.IntegerField(null=True),
        ),
    ]
