# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-29 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cq', '0005_auto_20180829_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgement',
            name='similarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judgements', to='cq.Similarity'),
        ),
    ]
