# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-30 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cq', '0005_auto_20180730_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='found',
            field=models.NullBooleanField(),
        ),
    ]
