# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-30 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cq', '0006_milestone_found'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='found',
        ),
        migrations.RemoveField(
            model_name='response',
            name='like_cnt',
        ),
        migrations.AddField(
            model_name='milestone',
            name='like_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
