# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-30 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cq', '0006_auto_20180830_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='code_second',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cq.Codesecond'),
        ),
    ]
