# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-05 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cq', '0007_auto_20180830_0532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='similarity',
            name='question_first',
        ),
        migrations.RemoveField(
            model_name='similarity',
            name='question_second',
        ),
        migrations.AlterField(
            model_name='judgement',
            name='question_first',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judgement_firsts', to='cq.Question'),
        ),
        migrations.AlterField(
            model_name='judgement',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='judgement',
            name='similarity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judgements', to='cq.Similarity'),
        ),
    ]
