# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-05 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cq', '0008_auto_20180905_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='similarity',
            old_name='similarity',
            new_name='score',
        ),
    ]
